### ISSUE TITLE
stones duplicate when thrown straight down at corpses

### ISSUE THREAD

**Issue by melodica2905** [melodica2905/hdest-melonades#4]
no idea why this is happening, leaving this here as a reminder for later

**Comment by melodica2905** [comment]
found the cause, it's happening when the destroy state lasts more than 0 tics

**Comment by melodica2905** [comment]
fixed in commit 4c5ee48

**Comment by ghost** [comment]
the destroy state needs to be at least one tic long, otherwise the roller will be deleted when it's entering the destroy state from HD's tick override, causing the VM to crash.
the duplication is most likely caused by the roller's state being set to `destroy` twice - from HD's tick method and your spawn2 state.

EDIT: adding back the `TNT1 A 1` at the end of `destroy` fixes the VM crash without bringing back the dupe - the extra tic in `death` must've fixed it.

**Comment by melodica2905** [comment]
I see, thanks for clearing that up, will fix now
